<h2><?php echo $this->escape($this->title); ?></h2>
<p>
You have just successfully installed the Zend Framework demoground.
</p>
<p>
This demoground reveals some of the main features of the Zend Framework:
</p>
<ul>
   <li>- MVC</li>
   <li>- Routing</li>
   <li>- Modules</li>
   <li>- and AMF remoting</li>
</ul>
<p>
Some of this features will be explained at my blog <a href="http://gertonscorner.wordpress.com" title="Gerton's corner">Gertonscorner</a>
</p>