<div id="logo">
   <h1>Gertons's corner</h1>
   <h2><a href="http://gertonscorner.wordpress.com/" title="">Zend framework demoground</a></h2>
</div>
<div id="authenticate">
   <?php echo $this->partial('partials/login.phtml', $this->loggedInUser); ?>
</div>
<div id="menu">
   <ul>
      <li><a href="/"  title="">Home</a></li>
      <li><a href="/"  title="">Forms</a></li>
      <li><a href="/admin" title="">Admin</a></li>
   </ul>
</div>