<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
  <?php echo $this->headMeta() ?>
  <?php echo $this->headTitle() ?>
  <?php 
        $this->headScript()->appendFile('/min/g=js'); 
        // output the javascript
        echo $this->headScript();
  ?>
  <?php echo $this->headLink()->appendStylesheet('/min/g=css') ?>
</head> 
<body>
   <div id="doc" class="yui-t5">
      <div id="hd">
         <?php echo $this->render('partials/header.phtml') ?>
      </div>
      <div id="bd">
	     <div id="yui-main">
	        <div class="yui-b">
	           <div id="left-block" class="yui-g">
	              <?php echo $this->layout()->content ?>
	           </div>
            </div>
	     </div>
	     <div id="right-block" class="yui-b">
	        <h3>Demoground News</h3>
	        <ul>
			  <li class="news">
				  <h4>September 2, 2009</h4>
				  <p><a href="#"> Duis tempor posuere diam. Suspendisse vel tellus quis nunc malesuada porta. &#8230;</a></p>
			  </li>
			  <li class="news">
				  <h4>June 23, 2009</h4>
				  <p><a href="#">Tempus Duis tempor posuere diam. Suspendisse vel tellus quis nunc malesuada porta. &#8230;</a></p>
			  </li>
			  <li class="news">
				  <h4>June 12, 2009</h4>
				  <p><a href="#">Tempus in, lacus. Duis tempor uspendisse vel tellus quis nunc malesuada porta. &#8230;</a></p>
			  </li>				  
		    </ul>
	     </div>
	  </div>
      
   </div>
   <div id="ft">
      <?php echo $this->render('partials/footer.phtml') ?>
   </div>
   <?php echo $this->render('partials/jquery_ready.phtml') ?>
</body>
</html>
