<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
  <?php echo $this->headMeta() ?>
  <?php echo $this->headTitle() ?>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.8.0r4/build/reset-fonts-grids/reset-fonts-grids.css"/>
  <?php echo $this->headLink()->appendStylesheet('/css/styles.css') ?>
</head> 
<body>
   <div id="doc3" class="yui-t3">
      <div id="hd">
         <h1><?php echo $this->escape($this->title); ?></h1>
      </div>
      <div id="bd"> 
	    <div class="yui-g"> 
	       <?php echo $this->layout()->content ?>
	    </div>
      </div>
      <div id="ft"><p>Footer</p></div>
   </div>
</body>
</html>
