<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
  <?php echo $this->headMeta() ?>
  <?php echo $this->headTitle() ?>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.8.0r4/build/reset-fonts-grids/reset-fonts-grids.css"/>
  <?php echo $this->headLink()->appendStylesheet('/css/styles.css') ?>
</head> 
<body>
   <div id="doc" class="yui-t7">
      <div id="hd">
         <div id="logo">
            <h1>Gertons's corner</h1>
            <h2><a href="http://gertonscorner.wordpress.com/" title="">Zend framework demoground</a></h2>
         </div>
         <div id="menu">
		    <ul>
			   <li><a href="#"  title="">Home</a></li>
			   <li><a href="#" title="">Admin</a></li>
		   </ul>
	     </div>
      </div>
      <div id="bd"> 
	    <div id="left-block" class="yui-g"> 
	       <?php echo $this->layout()->content ?>
	    </div>
      </div>
   </div>
   <div id="ft">
      <p>Copyright &copy; 2009. Design by <a href="http://www.metamorphozis.com/" title="Free Web Page Templates">Free Web Page Templates</a> | <a href="#">Privacy Policy</a> | <a href="#">Terms of Use</a> | <a href="http://validator.w3.org/check/referer" title="This page validates as XHTML 1.0 Transitional"><abbr title="eXtensible HyperText Markup Language">XHTML</abbr></a> | <a href="http://jigsaw.w3.org/css-validator/check/referer" title="This page validates as CSS"><abbr title="Cascading Style Sheets">CSS</abbr></a></p>
      <p>Design downloaded from <a href="http://www.free-css-layouts.com" title="Free CSS Layouts">Layouts</a></p>
   </div>
</body>
</html>