<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
  <?php echo $this->headMeta() ?>
  <?php echo $this->headTitle() ?>
  <?php 
        $this->headScript()->appendFile('/min/g=js'); 
        // output the javascript
        echo $this->headScript();
  ?>
  <?php echo $this->headLink()->appendStylesheet('/min/g=css') ?>
</head> 
<body>
   <div id="doc" class="yui-t7">
      <div id="hd">
         <?php echo $this->render('partials/header.phtml') ?>
      </div>
      
      <div id="bd"> 
	    <div id="left-block" class="yui-g"> 
	       <?php echo $this->layout()->content ?>
	    </div>
      </div>
   </div>
   <div id="ft">
      <?php echo $this->render('partials/footer.phtml') ?>
   </div>
   <?php echo $this->render('partials/jquery_ready.phtml') ?>
</body>
</html>